#!/bin/sh

if [ $# -ne 1 ];
then
    echo "Must specify which file to save!"
    exit 2
fi

cd `dirname $1`

file=`basename $1`

message=`mktemp --tmpdir journal.XXXXXXXX`

echo "Saving $file.\n" > $message

git diff -U0 $1 | sed -e "s/^@@/\n@@/" | grep -v '^\---\|^+++\|^diff\|^index'  >> $message

git add $file

git commit -F $message

rm $message

